### PR TITLE
Add a troubleshooting note for expired certificate error

### PR DESCRIPTION
**Pull request by shadyvb**
- ~Allow reinitiation of chassis on failure~
- Add a troubleshooting note for expired certificate error

This helps with certificate expiry issues, eg:

`Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification.`

### CODE REVIEW

**Comment by roborourke** [comment]
We could possibly make an extension to do this, we have this extension https://github.com/humanmade/platform_chassis_extension that essentially just collects the list of extensions we require in one place - a new extension could be added there so we can get this fix to everyone.

I'd ideally like to avoid folks having to install packages to get things working.

Is there any issue having this installed just generally you're aware of?

**Comment by shadyvb** [comment]
Hmmm, @roborourke does it update the box ? I doubt so. We can probably make it do that though if we need.

In the mean time, I'll probably open an issue to update the troubleshooting at Chassis/Chassis since that's where we refer to for troubleshooting steps, also I think it'd be beneficial for the wider audience of Chassis as well.

**Comment by roborourke** [comment]
Ah no, doesn't update the box - that would be a good addition to add to the upgrade command

**Comment by tomjn** [comment]
`ca-certificates` is needed for certificate trust chains to be updated going forward. It doesn't make sense as an extension as it should be taken care of by the box but isn't. VVV also installs another gnuTLS package that was needed for some environments to fully work with the certificate changes

**Pull request closed without merging**
